export const UPDATE_READING = 'UPDATE_READING';
export const UPDATE_READINGS = 'UPDATE_READINGS';
export const UPDATE_OPTIMIZED_VALUES = 'UPDATE_OPTIMIZED_VALUES';
export const SET_LANGUAGE = 'SET_LANGUAGE';
